CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability readability --epoch 50
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability completeness --epoch 50
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability grammar --epoch 50
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability readability --epoch 50 --model_name microsoft/deberta-v3-large
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability completeness --epoch 50 --model_name microsoft/deberta-v3-large
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability grammar --epoch 50 --model_name microsoft/deberta-v3-large
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability readability --epoch 50 --model_name roberta-base
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability completeness --epoch 50 --model_name roberta-base
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability grammar --epoch 50 --model_name roberta-base
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability readability --epoch 50 --model_name roberta-large
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability completeness --epoch 50 --model_name roberta-large
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability grammar --epoch 50 --model_name roberta-large
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability readability --epoch 50 --model_name bert-base-uncased
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability completeness --epoch 50 --model_name bert-base-uncased
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability grammar --epoch 50 --model_name bert-base-uncased
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability readability --epoch 50 --model_name bert-large-uncased
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability completeness --epoch 50 --model_name bert-large-uncased
CUDA_VISIBLE_DEVICES=1 python train_regression.py --ability grammar --epoch 50 --model_name bert-large-uncased